jaspervdj/hakyll

src/Hakyll/Core/Rules.hs
Someone else on the mailing list asked last month about using metadata to decide whether or not to compile something when defining `Rules`. This capability would solve a problem for me, too.
I realized all of the tools were already there in the form of the `getAllMetadata` function on the `MonadMetadata` typeclass. This PR just creates an alternative to `match` that also takes a predicate on metadata.
=> matchMetadata for examining metadata when defining rules

tests/Hakyll/Web/Template/Tests.hs
When running hakyll's test suit locally I noticed that a file named "foo" is left in the parent directory of the project after the test suit completes. It looks like this was added for debugging purposes at some point and was accidentally committed.
=> Remove test debug output

src/Hakyll/Init.hs
Previously, hakyll-init would create the cabal file with a name like
name.cabal.cabal.
=> Don't add .cabal extension twice in init

src/Hakyll/Web/Template/Context.hs
This way you don't need to use the  separator.
You can define your own.
=> Added support for a custom teaser separator

src/Hakyll/Web/Pandoc.hs, src/Hakyll/Web/Pandoc/FileType.hs
I choose Pandoc for my doc parser because it supports mediawiki. I'm loving Haskell and prefer writing my posts in *.mediawiki. So I add this support in Hakyll :)
=> add support for mediawiki

src/Hakyll/Web/Pandoc/Biblio.hs
For rationale, see:
https://github.com/mcmtroffaes/homepage/blob/master/posts/2015-01-09-hakyll-and-bibtex.markdown
The only thing I'm unsure about is passing the csl and bib files as strings: it works, but it may not be the "best" interface. I'm only starting to get to know hakyll's code base so I apologize in advance for my ignorance if I got this wrong.
=> Add convenience function pandocBiblioCompiler.

src/Hakyll/Web/Html.hs, tests/Hakyll/Web/Html/RelativizeUrls/Tests.hs
Similar to #134, this change enables the `poster` attribute of videos to be recognized as a URL and processed using `withURLs`. Here's where it's referenced in the [HTML standard](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-video-poster).
Thanks for maintaining hakyll!
=> Add "poster" as a URL attribute

src/Hakyll/Init.hs
When running `hakyll-init --help`, the current behavior is to generate a directory of `--help`.
But I think a more intended behavior would be providing help messages rather than creating the directory.
=> prevent hakyll-init from generating directory with leading hyphen(s)

hakyll.cabal
Hello,
I found need to mangle some `Template` contents in my Hakyll website. Everything is quite straightforward, the data structures explain themselves, but… they're not exposed!
I'm not saying that those functions should be exported through `Hakyll`, but I would really like to be able to explicitly `import Hakyll.Web.Template.Internal` into my code. See also [this excellent answer](http://stackoverflow.com/a/9198453/1048572) to the StackOverflow question "*How, why and when to use the “.Internal” modules pattern?*" for detailed argumentation.
=> Expose templating engine

src/Hakyll/Web/Feed.hs
The item's author is the item's author, not the feed's owner.
=> Item context has precedence before feed context

README.markdown
Use http://shields.io for a higher quality badge.
Here is a screenshot from my MacBook Pro highlighting the difference (new badge on the right):
=> Make Travis badge Retina ready

web/tutorials/01-installation.markdown, web/tutorials/02-basics.markdown
See also the mailing list thread: https://groups.google.com/forum/#!topic/hakyll/CR-k5YFi9WA
The only potential downside I can see to doing it this way is that you have to replace `./site <command>` with `stack exec site <command>`, and so this might 'break' other tutorials or materials that refer to Hakyll.
=> Recommend Stack in installation/basics tutorials

src/Hakyll/Web/Template/Context.hs
I've been using a `$snippet("...")$` for some time, which I find quite useful when I don't want my included files to be processed like templates, as happens with `$partial("...")$`. Typical use case, I want to include an extra Haskell file which contains `$`s and `<$>`s  and most of the file is eaten away. Might be useful to other people as well.
It requires something like this in the rules:
``` haskell
match "snippet.txt" $ compile getResourceBody
```
instead of
``` haskell
match "template.txt" $ compile templateCompiler
```
Let me know if I missed an existing solution; also, no hard feelings if this gets rejected. If there's a chance this gets in, I'll update with the doc in `Template/Internal`.
=> Add Snippet expression for snippet includes

src/Hakyll/Web/Paginate.hs
The code tried to generate Show instance for a function.
I don't know where it used to come from but it's not there
anymore. Build fails as:
[48 of 49] Compiling Hakyll.Web.Paginate ( src/Hakyll/Web/Paginate.hs, dist/build/Hakyll/Web/Paginate.o )
src/Hakyll/Web/Paginate.hs:40:17:
No instance for (Show (PageNumber -> Identifier))
(maybe you haven't applied enough arguments to a function?)
arising from the second field of ‘Paginate’
(type ‘PageNumber -> Identifier’)
Possible fix:
use a standalone 'deriving instance' declaration,
so you can specify the instance context yourself
When deriving the instance for (Show Paginate)
Change drops Show instance as it's not very useful.
Signed-off-by: Sergei Trofimovich <siarheit@google.com>
=> src/Hakyll/Web/Paginate.hs: Fix build failure

.travis.yml
Slightly hacky travis script.
Here's a log from my test: [here](https://travis-ci.org/sakshamsharma/hakyll/builds/134875314)
Caching is enabled, so it should not build all the dependencies every time.
Also, you need to override some of the travis phases or else it will try to run cabal, which will break during dependency resolution (and is not going to be of any use anyway).
=> Move to stack for travis CI testing.

web/tutorials/github-pages-tutorial.md
This fixes the incorrect `rsync` command, as noted in [this Google Group post](https://groups.google.com/forum/#!topic/hakyll/PBtPQ0PK-20). The new command is more conservative and preserves the `.git` folder and the `.gitignore` file.
=> Fix rsync command in GH Pages tutorial

src/Hakyll/Web/CompressCss.hs
we have less compression but we preserve correct CSS semantic
=> Fixes https://github.com/jaspervdj/hakyll/issues/323 

web/tutorials/01-installation.markdown
stack build complains if there is no stack.yaml so the previous comment is misleading for people who don't know what stack init does.
=> stack init is not really optional

hakyll.cabal
hakyll does not build with earlier versions of yaml that didn't provide `prettyPrintParseException`.
=> prettyPrintParseException was introduced in yaml-0.8.11

web/examples.markdown
=> Remove https://dikmax.name/ from examples.

web/tutorials/github-pages-tutorial.md
There are two changes:
1. Fixed `git fetch` to use `--all` flag
2. Added `.stack-work` to directories ignored by rsync, otherwise `.stack-work` gets deleted by rsync (Ouch!).  I also refactored the rsync command to be more readable.
=> Update git fetch and fix rsync for stack

hakyll.cabal, src/Hakyll/Web/CompressCss.hs, tests/Hakyll/Web/CompressCss/Tests.hs, tests/TestSuite.hs
CompressCss applied compressions (e.g. removal of whitespace) to CSS string constants. But those constants should retain their contents in the compressed CSS.
I've added some tests to demonstrate the behaviour, and I fixed the code. My new code is still rather verbose, which I think can be improved. I'm open to suggestions!
=> Bugfix: CompressCss modified CSS string constants which it should not do

src/Data/Yaml/Extended.hs, tests/Hakyll/Web/Template/Tests.hs, tests/data/example.md.metadata, tests/data/just-meta.html, tests/data/just-meta.html.out
If a numeric field contains an integer number, it should be shown
as an integer number.  Without this patch, the field:
answer = 42
would be shown as "42.0".  Before the introduction of YAML in
metadata, this was treated as a string and therefore shown as
just "42".  This patch reinstates the older (and IMHO correct)
behavior.
=> Fix integer fields in YAML metadata

web/tutorials/04-compilers.markdown
This information can only be found in the Haddocks documentation, but it's something you use often, so I've added it here.
=> Added information about the separator functionality in $for$.

src/Hakyll/Core/File.hs
I think copyFileCompiler should preserve the metadata of files, in particular the mtime.
This avoids unnecessary file transfers when deploying, e.g., with rsync.
(Note: copyFileWithMetadata has been introduced to directory rather recently, in version 1.2.6.0 from April 2016)
=> Preserve file metadata in copyFileCompiler

CODE_OF_CONDUCT.md
The reasons for having this are well-quantified at this point. From [the site itself](http://contributor-covenant.org/):
> Studies have shown that organizational cultures that value meritocracy [often result in greater inequality](http://asq.sagepub.com/content/55/4/543.short). People with "merit" are [often excused for their bad behavior](https://modelviewculture.com/pieces/the-dehumanizing-myth-of-the-meritocracy) in public spaces based on the value of their technical contributions. Meritocracy also naively assumes a level playing field, in which everyone has access to the same resources, free time, and common life experiences to draw upon. These factors and more make contributing to open source a daunting prospect for make people, especially women and other underrepresented people. …
=> Add the Contributor Covenant.

hakyll.cabal
0.10.5 added a new type `CLabel` to `Text.CSL.Reference`, which broke the orphan instance in `Web.Pandoc.Binary`.
Note also that according to PVP a client that defines an orphan instance **must** depend on the *minor* version of the package defining the type.
=> Tighten the dependency on pandoc-citeproc.

web/examples.markdown
I clicked all the links, looking for website ideas / potential code to use, removing the ones that are gone / different content. In one case, http://blog.darkfox.id.au/ , hakyll isn't being used.  In several cases, the source still exists but the website does not.
Also, when I was searching earlier I found this nice looking site that is not listed https://thibaud.dauce.fr/
=> Remove non-existent links

lib/Hakyll/Commands.hs
I'd like to add tests to my website and run them before it's deployed. Hakyll provides a link checker out-of-the-box that I'd like to integrate in my tests in a clean way.
The `check` function is exported but on of its parameters - the `Check` type - is not exported making it impossible to use it outside the Hakyll project. This means that the only way to run it right now is to ask an external tool like `stack` to run it and then somehow parse the resulting output to check that no error occurred. An sample implementation of this approach is available [here](https://github.com/futtetennista/futtetennista.github.com/commit/154211c694d6dbb6c36d5223cc57e745d8a51857). I think it's safe to affirm that this approach is far from being ideal.
Export the `Check` type and its type constructors so …
=> Export `Check` type

lib/Hakyll/Web/CompressCss.hs, tests/Hakyll/Web/CompressCss/Tests.hs
According to Mozilla Developer Network, “The + and - operators must always be surrounded by whitespace.”.
=> Fix compression of calc() in CSS

web/examples.markdown
Hey, thanks for maintaining Hakyll :)
I'd like to add this site to the list of examples. There's nothing notable about this site except that it doesn't use Hakyll templating. Instead it uses [Lucid](https://hackage.haskell.org/package/lucid) to define the HTML and passes along the metadata in a record type.
Cheers,
Aaron
=> Add spyhop.cafe to example sites

stack.yaml
This allows `stack --nix build` to work.
=> stack.yaml: configure nix options

hakyll.cabal, stack.yaml
Similar to these issues:
- [pthread link errors on linux with GHC 8.2 #4130](https://github.com/jgm/pandoc/issues/4130)
- [Error building on Ubuntu 16 #311](https://github.com/jgm/pandoc-citeproc/issues/311)
=> Added -threaded to ghc-options. pthread link errors on linux with GHC 8.2

hakyll.cabal, lib/Hakyll/Web/Feed.hs, lib/Hakyll/Web/Template.hs, lib/Hakyll/Web/Template/Internal.hs
This is very useful when hakyll is used to build statically linked binary in which case it would make sense to have a way to provide template files from a current working directory instead of fetching it from `data-files` that is very specific to where haskell code was built (e.g. build server).
I have elaborated on this a bit in my blog post [here](http://www.kuznero.com/posts/haskell/building-statically-linked-binaries.html#data-files-in-dependencies).
=> Load a template from a local files if present then fallback to embedded files

hakyll.cabal, lib/Hakyll/Web/Pandoc/Biblio.hs, stack.yaml, tests/Hakyll/Core/Provider/Tests.hs, tests/Hakyll/Core/Rules/Tests.hs, tests/Hakyll/Core/Store/Tests.hs, tests/Hakyll/Core/UnixFilter/Tests.hs, tests/Hakyll/Web/Html/Tests.hs
- Bump binary to 0.9
- Bump pandoc to 2.1
- Bump pandoc-citeproc to 0.13
- Bump http-types to 0.11
- Bump QuickCheck to 2.11
- Bump tasty to 1.0
- Bump tasty-hunit to 0.10
- Remove system-filepath dependency
=> Various dependency bumps

lib/Hakyll/Check.hs, lib/Hakyll/Core/Compiler/Internal.hs, lib/Hakyll/Core/Identifier/Pattern.hs, lib/Hakyll/Core/Routes.hs, lib/Hakyll/Core/Rules/Internal.hs, lib/Hakyll/Web/Template/Context.hs
Ensures forwards compatibility with future Haskell/GHC releases as the Semigroup/Monoid Proposal is gradually implemented.
Closes #525 and #536.
=> Add Semigroup instances for existing Monoids

web/examples.markdown
Another edition of https://github.com/jaspervdj/hakyll/pull/569 , since I'm revisiting the idea of building my site using hakyll!  I've done the same thing again of opening nearly every example hakyll website, to find ideas and code that I can reuse.
Removes the following due to no longer existing or not using hakyll:
* abizern.org says it's using Hugo & Goa
* covariant.me is no longer up, and neither is the repo
* rockymadden.com just redirects to github, and the rockymadden-web repo no
longer exists.
* blog.dshevchenko.biz no longer exists, and neither does the repoo
* jozefg.bitbucket.org is no longer up.  The repo is still up, but I couldn't
find a good archive.org for it.  The URL just redirects to bitbucket.org
* rohanjain.in now uses Hugo
* ruudvanasseldonk.com now uses a custom …
=> Adjust links to examples of hakyll 4 sites

lib/Hakyll/Web/Template/Context.hs, tests/Hakyll/Web/Template/Context/Tests.hs, tests/data/posts/2018-09-26.md
Drop the file extension when parsing the date from the filepath of a resource.
This fixes a bug in which Hakyll is unable to parse the date from a filepath and throws an error when the file has a name like `posts/2018-09-26.md` because the extension becomes part of the day value.
=> Drop extension when parsing dates in filepaths

lib/Hakyll/Core/Store.hs
I have a somewhat pages lookup-heavy site (lots of structure with autogenerated TOCs), and profiling shows `hash` is responsible for 40% of MUT time and roughly 45% of allocations. Replacing `concatMap` over `printf` with a bytestring-operating base16 encoding makes `hash` go away from the first lines of the profile and reduces site build time from ~10 seconds to 5 seconds for me (which looks like a nice improvement!).
I guess the names of the cached data are changed with this modification, but that's a matter of `site clean` (or `site rebuild`) anyway.
Hopefully you don't mind an additional dependency on base16-bytestring!
=> Use Data.ByteString.Base16.encode.

lib/Hakyll/Web/Feed.hs
An example usage is as follows:
```haskell
customRenderAtom :: FeedConfiguration -> Context String -> [Item String] -> Compiler (Item String)
customRenderAtom config context items = do
atomTemplate     <- unsafeCompiler $ readFile "templates/atom.xml"
atomItemTemplate <- unsafeCompiler $ readFile "templates/atom-item.xml"
renderAtomWithTemplates atomTemplate atomItemTemplate config context items
```
This should also fix #625 as people will be able to add custom templates with tags.
=> Adds support for rendering feeds with custom templates

tests/Hakyll/Core/UnixFilter/Tests.hs
Corrected an assertion that just seems to be out-of-date.
Tests run locally:
```
All 133 tests passed (1.10s)
hakyll-4.12.4.0: Test suite hakyll-tests passed
Completed 2 action(s).
Updating Haddock index for local packages in
/Users/js033433/Software/haskell/hakyll/.stack-work/install/x86_64-osx/nightly-2018-08-29/8.4.3/doc/index.html
Updating Haddock index for local packages and dependencies in
/Users/js033433/Software/haskell/hakyll/.stack-work/install/x86_64-osx/nightly-2018-08-29/8.4.3/doc/all/index.html
Haddock index for snapshot packages already up to date at:
/Users/js033433/.stack/snapshots/x86_64-osx/nightly-2018-08-29/8.4.3/doc/index.html
```
=> Corrected assertion in unixFilterError test. Fixes #669

web/examples.markdown
I recently shifted both my website and its source repository, so I've updated the links in the examples file.
=> Update examples.markdown with new personal blog link

hakyll.cabal
Since I want to use Hakyll with lts-13.x, I updated the old dependencies.
Note: I used Travis CI for testing. Compared with CircleCI, I did not have to make comlicated settings. I might possibly send a pull request to update CI relationship. It was hard to use TravisCI in the past, but as GHC's perfomance got higher, it's okay now!
Squashed: https://github.com/Hexirp/hakyll/tree/lts-13.0
=> Update old dependencies for lts-13.x

lib/Hakyll/Web/Tags.hs
`getCategory` functions similarly to `getTags` and seems to be a pretty useful function to have.
=> Expose `getCategory` in Haskell.Web.Tags

web/tutorials/01-installation.markdown
This is more consistent since the previous instructions use `stack`. It's also a huge trip up if multiple versions are somehow installed (like via the AUR).
=> docs: Update tutorial for consistent stack use

lib/Hakyll/Web/Feed.hs
I like following, has written a context to complement from the file name `published`.
[www.ncaq.net/site.hs at d8b7eb3426eae36ee0ea5788f32306b9ffa6f9f2 · ncaq/www.ncaq.net](https://github.com/ncaq/www.ncaq.net/blob/d8b7eb3426eae36ee0ea5788f32306b9ffa6f9f2/site.hs#L120)
Looking at feed today, I noticed that time is not reflected in `published`.
This is because `getItemUTC` overwrites my `published`.
Adding a format to `getItemUTC` was not a solution because I live with JST.
Also, it is not realistic to write `published` in the yaml metadata of all files, and I think that you want to be delivered as JST as much as possible.
Since `updated` does not overwrite the context, I tried to rewrite so that `published` does not overwrite the context.
I have confirmed in the local environment that all …
=> fixed: auto complete `published` overwrites user's context

hakyll.cabal
Tests appear to run fine (building on NixOS).
=> Bump QuickCheck to 2.13

hakyll.cabal
This probably fixes a build error with the Hackage tarball of 4.13.0.0.
I noticed that the files
```
tests/data/embed.html
tests/data/posts/2019/05/10/tomorrow.md
```
are missing in the [hackage tarball](https://hackage.haskell.org/package/hakyll-4.13.0.0/hakyll-4.13.0.0.tar.gz), but are present in the Git repository. I guess adding them to `Extra-source-files` in `hakyll.cabal` fixes the build errors I experienced in [Nixpkgs](https://github.com/NixOS/nixpkgs/):
```
...
Preprocessing test suite 'hakyll-tests' for hakyll-4.13.0.0..
Building test suite 'hakyll-tests' for hakyll-4.13.0.0..
[ 1 of 19] Compiling TestSuite.Util   ( tests/TestSuite/Util.hs, dist/build/hakyll-tests/hakyll-tests-tmp/TestSuite/Util.o )
[ 2 of 19] Compiling Hakyll.Web.Template.Tests ( …
```
=> add missing files to hakyll.cabal

src/Init.hs
used to be:
```
$ hakyll-init -h
Usage: hakyll-init[-f] <directory>
```
=> hakyll-init: fix spacing of command line usage

lib/Hakyll/Preview/Server.hs
This fixes out of order console messaging in the case of errors
binding to the configured address, though the message order is
still a bit weird.
Before:
```
$ stack exec site watch
Initialising...
Creating store...
site: Network.Socket.bind: resource busy (Address already in use)
Creating provider...
Listening on http://127.0.0.1:8000
```
After:
```
$ stack exec site watch
Listening on http://127.0.0.1:8000
Initialising...
Creating store...
Creating provider...
site: Network.Socket.bind: resource busy (Address already in use)
```
=> Flush log before starting web server

lib/Hakyll/Core/Identifier.hs, lib/Hakyll/Web/Feed.hs
This commit fixes two bugs related to path separator.
1. The 'makeRelativeToProject' reads files according to those filepaths. Therefore, compilation will fail if its path separator are wrong.
2. When converting to the 'Identifier', incorrect path separator are mixed, which causes file loading to fail.
See also: #640, #644, #645, #649
=> Fix about file path for compatibility with Windows

lib/Hakyll/Main.hs
Resolves #751
I have two example commits on my own site that use this:
- [This first example simply uses `defaultParserPure`](https://github.com/jhmcstanton/jhmcstanton.github.io/commit/2220206fdd88a915f67c05929acde376ab23e97b)
- [This example makes use of a custom `SiteOptions` type](https://github.com/jhmcstanton/jhmcstanton.github.io/commit/2ebe9deda6a1438096b9a008d9fb7438c280cf67#diff-d969b25c2913c74b1bb1fb5b91807fffR19)
=> Expose CLI arg parser internals

hakyll.cabal, lib/Hakyll/Core/Store.hs
'cryptohash' is deprecated. The package description says, "please use
cryptonite for new projects and convert old one to use cryptonite."
=> Use 'cryptonite' instead of 'cryptohash'

stack.yaml
I bump stack resolver version to lts-13.30. And I clean the extra-deps field
because those packages are already included in lts-13.30.
=> Clean stack.yaml

web/tutorials/01-installation.markdown
The command as it was resulted in an error in the latest NixOS release. The changed command installs hakyll in the user environment as intended.
=> Fix installation command on NixOS

data/example/site.hs
In the default site generated by Hakyll, `index.html` has specified the filed `title` in its front matter, but it will always been overridden by `constField "title" "Home"` in `site.hs`.
It is a very minor issue, but it may cause confusion to newcomers.
=> Remove constant field title for index.html in the example site

lib/Hakyll/Commands.hs
Fixes compile-time error related to `MonadFail` on Windows PCs.
See #764 for more details
=> Fix for #764 (Windows issue only)

lib/Hakyll/Core/Identifier.hs, lib/Hakyll/Core/Identifier/Pattern.hs, tests/Hakyll/Core/Identifier/Tests.hs
This pull request aims to fix issue #766 , where `Rules` were not firing properly on Windows.
Files on Windows were not being captured properly by `Hakyll.Core.Identifier.Pattern.capture`. To fix this, all paths becoming `Identifier`s are being normalized to have the Windows path separator `\\`. This requires modification of `Hakyll.Core.Identifier.Pattern.fromGlob` function. Also, regex matching on Windows paths needed to change a little.
After this fix, the test site produced by `hakyll-init` compiles properly.
I also want to point out that trying to glob `\\*.jpg` is invalid on Windows, so I removed this test case. This also simplifies the parsing of glob patterns.
=> Fix for filepaths matching on Windows.

.github/workflows/main.yml, README.markdown, lib/Hakyll/Core/Identifier/Pattern.hs, lib/Hakyll/Core/Routes.hs, lib/Hakyll/Core/Util/String.hs, lib/Hakyll/Web/Html.hs, tests/Hakyll/Core/Routes/Tests.hs, tests/Hakyll/Core/Rules/Tests.hs, tests/Hakyll/Core/UnixFilter/Tests.hs, tests/Hakyll/Web/Html/Tests.hs, tests/Hakyll/Web/Template/Tests.hs
Hello,
Following #778 , I noticed that a few tests did not pass on Windows. This pull request fixes a few things, including tweaked expected test values (e.g. with newlines `\r\n` instead of `\n`)
I also noticed that `gsubRoute` did not fire properly due to Regex not matching Windows path separators. This also has been fixed.
I noticed that the `toUrl` function also did not always work with Windows file paths, and this has been fixed as well. I added a test to ensure no regressions.
At this time, all tests pass on Windows!
@jaspervdj, what do you think of adding Windows CI to Github Actions? I took care of this in this PR as well. I can commit to fix things specific to Windows for the foreseeable future.
=> Miscellaneous Windows-specific fixes and CI

web/tutorials/01-installation.markdown
Hakyll has been available in the Debian stable release for a while now so this patch makes it clear one does not need to use Debian unstable to install a package for Hakyll.
=> Update a reference to Debian stable

hakyll.cabal
Hej
I tried building hakyll using Nix where currently it is marked as broken because pandoc 2.10 can not be satisfied by nix since 2.11 is out.
I patched the cabal file manually (extending the pandoc version constraints to include 2.11) and my blog still compiles.
This PR just upstreams that change.
Probably there might be incompatibilities I just missed, any hints how to assess this and make hakyll compatible with the latest pandoc?
=> Bump pandoc version

lib/Hakyll/Web/Template/Context.hs
The version of package `time` is required to be `>= 1.8` 
https://github.com/jaspervdj/hakyll/blob/8afbb62ed5e969d78d8664df205646504f52f278/hakyll.cabal#L193
so the conditional compilation below 
https://github.com/jaspervdj/hakyll/blob/8afbb62ed5e969d78d8664df205646504f52f278/lib/Hakyll/Web/Template/Context.hs#L467-L472
is not needed anymore.
=> Remove unnecessary conditional compilation for parseTimeM

lib/Hakyll/Core/File.hs
Patch by @gwern: https://github.com/jaspervdj/hakyll/issues/786#issuecomment-725733675
Fixes #786.
=> Add symlinkFileCompiler (by Gwern)

stack.yaml, stack.yaml.lock
This also bumps GHC versions from 8.8.3 to 8.8.4.
=> Bump Stackage LTS to 16.21

.github/workflows/main.yml
This update is necessary since actions/setup-haskell@1.1.1 that we were using required `add-path`, which [was removed yesterday](https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16) (after two weeks of being deprecated due to some CVE).
=> Update actions/setup-haskell to 1.1.3

.github/workflows/main.yml
This removes the need for a workaround on Windows.
=> Update actions/setup-haskell to 1.1.4

hakyll.cabal, tests/Hakyll/Web/Pandoc/Biblio/Tests.hs, tests/data/biblio/biblio01-pre-pandoc-2.11.3.golden
The new version started wrapping Biblio references into \<p> tags, so we now keep two different golden files for different Pandoc versions.
I had to add Pandoc to dependencies of the test suite, otherwise GHC won't define `MIN_VERSION_pandoc` macro.
=> Fix golden test failing with pandoc >= 2.11.3

lib/Hakyll/Web/Pandoc.hs
I don't know if this is actually helpful, but I got stuck trying to apply transformations to source files before passing them into `pandocCompilerWithTransformM`. 
For context - the current implementation of `pandocCompilerWithTransformM` calls `getResourceBody` in its implementation, but it would be nice to have it more open so that pre-pandoc transformations can be done, along with custom traversals of the pandoc AST. There's already `renderPandocWith` which takes in an item, but no variation that allows for a `Pandoc -> Compiler Pandoc` function to be passed in as well. 
I'm using this on my personal site already and it's pretty useful - I have some pages where I'd like to apply `functionField`s before passing them off to pandoc (e.g. macros for embedding links to SVGs). 
The function …
=> Added a modified `pandocCompilerWithTransformM` that takes in an item as an extra argument

hakyll.cabal
This passed on my machine:
cabal test all -j --enable-tests --constrain 'pandoc == 2.12'
=> Allow pandoc 2.12

hakyll.cabal
It should work, I'm guessing, not much has changed, so let's see if CI tests pass?
Do drafts go into CI pipeline? I guess we'll see...
EDIT: build seems to be successful, at least on some GHC versions with the newer pandoc, so marking this as non-draft.
=> Allow pandoc 2.13

hakyll.cabal, web/index.markdown, web/templates/tutorial.html
There's no mention of this on the issue tracker, so here's my recap of
what led to this change.
There is some drama around Freenode. Their volunteer staff quit[1]. Then
the new-ish management started enacting strange policy changes[2] and
take over the channels[3]. On June 26th 2021 Freenode's bot tried to
take over #hakyll, but failed; however, it did succeed in #haskell and
many, many other channels.
For the preceding week, me and IRC user henk were trying to move the
channel off the Freenode, either to Libera.Chat or OFTC. Jasper, the
founder of Hakyll, was absent from IRC and didn't respond to my emails.
Me and henk are the most active IRC users on the channel. Also, I have
Collaborator access to the repo, and henk has chanop access to the IRC
channel. We believe that at this time, …
=> Docs: IRC channel moved from Freenode to Libera.Chat

hakyll.cabal, lib/Hakyll/Core/Runtime.hs, src/Init.hs, tests/Hakyll/Core/Runtime/Tests.hs
Hello,
This is a PR to make hakyll's runtime concurrent. 
The general idea is based on #725. That particular implementation incorrectly identified a dependency cycle [in my personal website](https://github.com/LaurentRDC/personal-website) that did not exist. Hence, this PR includes more robust dependency cycle checking based on `Data.Graph`. A test case has been added to ensure this works.
The concurrency is implemented as follows.
1. Identify all items that need to be compiled;
2. Compile all items concurrently. Items that compiled successfully are removed from the todo list, while those with dependencies are kept;
3. The remaining todo and their dependencies are checked for cycles in a single thread;
4. Go to step 1 until all items have been compiled.
```haskell
pickAndChase :: Runtime …
```
=> Async runtime with graph-based dependency cycle checks

hakyll.cabal
This builds with GHC 9 as `cabal build --enable-tests --constrain 'template-haskell == 2.17.0.0' --constrain 'time == 1.11.1.2' --constrain 'file-embed == 0.0.14.0' `, and tests pass too.
=> Bump some more dependencies

lib/Hakyll/Web/Html.hs, tests/Hakyll/Web/Html/Tests.hs
Hello! I found myself in a spot where I needed to _really_ demote some headers, and I thought that other people might find this feature useful.
I've added a new function `demoteHeadersBy` which takes an argument `n > 0` and applies the demotion down no further than `h6`. The existing `demoteHeaders` function is now just an alias of `demoteHeadersBy 1` and retains its existing functionality.
Let me know how this looks and if I need to add or change anything. I didn't find a formal guide for contributing code so I'm just tossing this out there :)
=> Allow demotion of headers by a given amount

lib/Hakyll/Core/Dependencies.hs, lib/Hakyll/Core/Rules.hs
Compilers that use data from sources other than local files may need
to be recompiled, but Hakyll's file-based dependency checking does
not handle this situation.
Add a new kind of dependency called 'AlwaysOutOfDate'.  If an item
has this dependency, it will be unconditionally rebuilt.
Also add the 'forceCompile' rule modifier, which is a user-friendly
way to force recompilation of specific items.  Example usage:
forceCompile $ create ["foo"] $ do
route $ idRoute
compile $ unsafeCompiler $ doSomeIO
=> add 'forceCompile' rules modifier

web/tutorials/github-pages-tutorial.md
Report and fix by @alexandroid000. Fixes #860.
=> Avoid "Empty 'do' block" error in GitHub tutorial

lib/Hakyll/Web/Tags.hs
Recently had a situation where we wanted two separate fields for tags, one for a simple tag cloud and another for a more robust index of keywords, and implemented these in our site generator. This just refactors `getTags` and `buildTags` to easily allow users to pick an arbitrary field for tag-like data without needing to peek into the source.
=> Supporting different field names for tags.

hakyll.cabal, lib/Hakyll/Core/Runtime.hs
Proposing a slightly different choice of concurrent variable type to https://github.com/jaspervdj/hakyll/pull/844.
=> Hakyll.Core.Runtime: use `MVar` instead of `TVar`

lib/Hakyll/Core/Configuration.hs, lib/Hakyll/Preview/Poll.hs
https://github.com/jaspervdj/hakyll/issues/845
Add a predicate to the configuration to suppress rebuild events in watch mode when a file is touched that makes the predicate true.
=> Allow configuring dirs/files to be ignored in watch mode

hakyll.cabal, lib/Hakyll.hs, lib/Hakyll/Web/Meta/JSONLD.hs, lib/Hakyll/Web/Meta/OpenGraph.hs, lib/Hakyll/Web/Meta/TwitterCard.hs
This PR adds a simple way to add OpenGraph, Twitter Card and JSON-LD metadata
to the HTML for an article.  These standards support rich search results and
better presentation of links when posting on social media, etc.
I believe these features would be appreciated by many users of Hakyll.  And
they introduce no new dependencies (one transitive dependency - *aeson* -
becomes a direct dependency).  Hence I propose inclusion as part of the
*hakyll* package itself.
=> add support for OpenGraph and JSON-LD metadata

lib/Hakyll/Web/Pandoc/Biblio.hs
**Proposal:**
The [`Hakyll.Web.Pandoc.Biblio`](https://hackage.haskell.org/package/hakyll-4.14.0.0/docs/Hakyll-Web-Pandoc-Biblio.html) module should export the `unCSL` function.  
This module already exports `unBiblio` which is quite similar, so I'm guessing the exclusion of `unCSL` is just an oversight.
**Context:**
I want to use Pandoc citations, but I can't see how to use the existing `pandocBiblioCompiler` in combination with a compiler that I use (modified from [this blog post](https://ifazk.com/blog/2018-11-20-JavaScript-free-Hakyll-site.html)) to render KaTeX equations.  It looks like I will need to write a modified [`readPandocBiblio`](https://github.com/jaspervdj/hakyll/blob/master/lib/Hakyll/Web/Pandoc/Biblio.hs#L86) function, which makes use of the `unCSL` function.
Thanks!
=> Export `unCSL` from `Hakyll.Web.Pandoc.Biblio`

hakyll.cabal
Tested with `for action in build test ; do cabal $action --enable-tests --constrain 'file-embed == 0.0.15.0' || break ; done`.
=> Allow file-embed 0.0.15.0

.github/workflows/main.yml
Normally we exclude older compilers on macOS and Windows, but since
GHC 9 is fairly new still, I chose to keep GHC 8.10 in the matrix for
a while longer.
=> CI: add GHC 9, bump GHC 8.10 and Stack

lib/Hakyll/Core/Compiler/Internal.hs, lib/Hakyll/Core/Compiler/Require.hs, lib/Hakyll/Core/Runtime.hs
Currently, `loadAllSnapshots` loads snapshots one at a time,
emitting a `CompilerRequire` intermediate result for each one.  This
results in additional iterations of `pickAndChase`, with extra
computation to test for dependency cycles each time.
But for `loadAllSnapshots`, we immediately know all the depenencies
to add.  Therefore, update the `CompilerRequire` constructor to have
a list of `(Identifier, Snapshot)` pairs.
Extract snapshot loading to a new `loadSnapshotCollection` helper
function, which operates on a collection of required snapshots:
loadSnapshotCollection
:: (Binary a, Typeable a, Traversable t)
=> t (Identifier, Snapshot) -> Compiler (t (Item a))
`t` can be instantiated at `[]` to load multiple snapshots, emitting
a single `CompilerRequire` intermediate result for the …
=> loadAllSnapshots: emit all dependencies at once

lib/Hakyll/Core/Compiler/Internal.hs
Use `Data.Set.filter` instead of converting to list, filtering the
list then building a new `Set`.  This results in a ~3% speedup for
my site:
```
% hyperfine \
--prepare './site-master clean' './site-master build' \
--prepare './site-set    clean' './site-set    build'
Benchmark #1: ./site-master build
Time (mean ± σ):      6.855 s ±  0.111 s    [User: 6.567 s, System: 0.261 s]
Range (min … max):    6.757 s …  7.122 s    10 runs
Benchmark #2: ./site-set    build
Time (mean ± σ):      6.658 s ±  0.093 s    [User: 6.378 s, System: 0.258 s]
Range (min … max):    6.488 s …  6.842 s    10 runs
Summary
'./site-set build +RTS -N1' ran
1.03 ± 0.02 times faster than './site-master build +RTS -N1'
```
=> compilerGetMatches: improve performance

lib/Hakyll/Core/Compiler.hs, lib/Hakyll/Core/Rules.hs
Commit 6885325146aa46adf255c55de0e0345a0f84961e added the
`AlwaysOutOfDate` dependency type, and the `forceRecompile` rules
modifier.  Users can use this to force recompilation of items that
use `unsafeCompiler` to run IO.
But it would be more convenient to have a `Compiler` that runs `IO`
actions and forces recompilation.  Add the `safeCompiler` function
for this purpose.
=> add recompiling `safeCompiler :: IO a -> Compiler a`

lib/Hakyll/Commands.hs, lib/Hakyll/Core/Runtime.hs, lib/Hakyll/Main.hs, tests/Hakyll/Core/Runtime/Tests.hs, tests/Hakyll/Web/Pandoc/Biblio/Tests.hs
Add a --dry-run option to the build command.  In this mode, build
prints the list of items that need to be (re)compiled.
This mode is also useful for benchmarking the initialisation phase.
=> build: add --dry-run option

lib/Hakyll/Web/Pandoc.hs, lib/Hakyll/Web/Pandoc/Biblio.hs, lib/Hakyll/Web/Pandoc/FileType.hs, tests/Hakyll/Web/Pandoc/FileType/Tests.hs
Pandoc can now handle Jupyter notebooks. Add support for this format to Hakyll.
=> Add support for  jupyter notebooks

lib/Hakyll/Web/Pandoc/Biblio.hs
`processPandocBiblio` works on `Item Pandoc` as opposed to `Item
String`.  This allows composition with other `Pandoc` and source transforming functions.
`readPandocBiblio` retains the previous behavior.
=> add `processPandocBiblio` and use it in `readPandocBiblio`

web/tutorials/external-jekyll-style-urls-with-hakyll.markdown
This repo and the [companion repo](https://github.com/aherrmann/jekyll_style_urls_with_hakyll_examples/blob/master/site.hs) (which doesn't seem to be linked in the post for some reason) were very helpful and saved me a whole bunch of trouble in porting my blog from Jekyll to Hakyll without breaking too many deeplinks. I figured it'd be a good inclusion here.
=> Add Jekyll Style URLs with Hakyll to tutorials

.github/workflows/main.yml
GHC 9 on Windows fails a lot with an error mentioning
"renameFile:renamePath:MoveFileEx". An upstream ticket about this[1] was
fixed by a change to Cabal, so maybe upgrading will help us.
https://gitlab.haskell.org/ghc/ghc/-/issues/18274
=> CI: Disable GHC 9 on Windows

hakyll.cabal
The `array` dependency was introduced in #844 to perform topological sorting of requirements. This functionality was improved in #880 which means that the `array` dependency is superfluous.
=> Remove `array` dependency

.github/workflows/main.yml
This should save us from mistakes that will only become apparent once
the package gets published to Hackage.
Fixes #887.
=> Add CI job to test sdist package

hakyll.cabal
`for action in build test ; do cabal $action --enable-tests --constrain 'pandoc == 2.16' || break ; done` passed.
Once this is merged, I will also make a Hackage revision.
=> Allow pandoc 2.16

hakyll.cabal, lib/Hakyll/Web/Pandoc.hs
Both of these commands passed:
```
$ cabal build --enable-tests --constrain 'pandoc == 2.16.2' && cabal test --constrain 'pandoc == 2.16.2' 
$ cabal build --enable-tests --constrain 'pandoc == 2.17.0.1' && cabal test --constrain 'pandoc == 2.17.0.1' 
```
I'll make a new release right after this is merged.
=> Allow pandoc 2.17

hakyll.cabal
This passed:
```
for action in build test; do cabal $action --enable-tests --constrain 'optparse-applicative == 0.17.0.0' || break; done
```
=> Allow optparse-applicative 0.17

web/tutorials/robertwpearce-01-setup-and-initial-customization.html
The URL must have changed at some point, as I can even find some dead links on that person's website.  I rebuid the site with the `buildWebsite` flag and then checked things via `stack exec hakyll-website watch` and it looked fine to me—hopefully that was correct
=> web: Fix link to part one of Robert Pearce's tutorial

hakyll.cabal
This passed:
```
$ for action in build test ; do cabal $action --enable-tests --constrain 'pandoc == 2.18' || break ; done
```
=> Allow pandoc 2.18

hakyll.cabal
`for action in build test ; do cabal $action --enable-tests --constrain 'text == 2.0' || break ; done` passed.
=> Allow text 2.0

hakyll.cabal
`for action in build test ; do cabal $action --enable-tests --constrain 'pandoc == 2.19' || break ; done` passed.
=> Allow pandoc 2.19

hakyll.cabal
`for action in build test ; do cabal $action --enable-tests --constrain 'vector == 0.13.0.0' || break ; done` passed.
=> Allow vector 0.13.0.0

hakyll.cabal
`for action in build test ; do cabal $action --enable-tests --constrain 'aeson == 2.1.0.0' || break ; done` passed.
=> Allow aeson 2.1.0.0

lib/Hakyll/Web/Template/Context.hs
Add one more date format for dateField
Used in Germany, Norway, France and some other countries
Because usage of DD.MM.YYYY in metadata is native while YYYY-MM-DD is alien for us
=> Add one more date format for dateField

hakyll.cabal
`for action in build test ; do cabal $action --enable-tests --constrain 'fsnotify == 0.4.0.0' --flags 'previewServer watchServer' || break ; done` passed.
=> Allow fsnotify 0.4.0.0

hakyll.cabal
This passed: `for action in build test ; do cabal $action --enable-tests --constrain 'resourcet == 1.3.0' || break ; done`.
=> Allow resourcet 1.3

lib/Hakyll/Main.hs
This reduces the amount of copy-pasting required to add custom sub-commands to the hakyll cli.
For my personal hakyll-created website, I implemented a `myHakyll` function that uses a custom `myOptionsParser` and `myCommandParser` to allow for custom command line options and commands:
```haskell
data MyCommand = HakyllCommand Command
| MyCustomCommand
data MyOptions = MyOptions { verbosity :: Bool, myOptCommand :: MyCommand }
myHakyll :: Configuration -> Rules a -> IO ()
myHakyll conf rules = do
args <- myParser conf
case myOptCommand args of
HakyllCommand com
-> hakyllWithArgs conf (Options (verbosity args) com) rules
GenerateWeeklyChallenges -> generateNewChallengeFiles
```
While I want to add some custom commands, I also would like to keep all the base commands provided by `hakyll`. …
=> Factor out and export defaultCommands

hakyll.cabal
Tested locally with GHC 9.4.3 by running `for action in build test ; do cabal $action --enable-tests || break ; done`
=> Allow template-haskell 2.20 (GHC 9.4.3)

web/examples.markdown
I'm currently doing a partial rewrite of scr.stunts.hu, which makes it difficult to keep the literate source file that was linked from here updated. If I ever get to make the site repository public, I'll bring it back here.
=> Remove scr.stunts.hu from examples

hakyll.cabal, lib/Hakyll/Web/Html.hs
This passes:
```
$ for action in build test ; do cabal $action --enable-tests --constrain 'mtl == 2.3.1' || break ; done
```
=> Allow mtl 2.3

web/examples.markdown
I recently noticed that <https://www.haskell.org/> is generated with Hakyll, but that it's not in the list of examples.  I think Hakyll deserves to toot its horn a little bit and include it as an example. :)
=> Add www.haskell.org to examples.

.github/workflows/main.yml
New versions are the ones recommended by `ghcup tui`. Also, the Stack CI job uses the same GHC (9.2.5) as the Stackage LTS snapshot we're using does (lts-20.10).
=> CI: update Stack and GHC

lib/Hakyll/Web/Meta/TwitterCard.hs
> Twitter’s parser will fall back to using property and content, so there is no need to modify existing Open Graph protocol markup if it already exists.
>
> [Getting started with Cards | Docs | Twitter Developer Platform](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started)
It may be usable for now since it is fallback, but it is better to output the correct one just in case.
=> fix: Twitter Card use `name` instead `property`

lib/Hakyll/Check.hs, lib/Hakyll/Core/Configuration.hs
This adds a configuration option to customize which files are determined to be HTML files to check links for with `site check`.
This should help resolve https://github.com/jaspervdj/hakyll/issues/742.  While it does not make Hakyll check links for all HTML files regardless of extension, it does make it possible to configure Hakyll to do so.
=> Allow configuration of files to be checked for links.

web/examples.markdown
A lot of examples have accumulated, but over the years many of them have disappeared or moved on.  I was looking at the source code for the examples to learn anything that I might later find useful on my own site; noting which sites have disappeared, changed addresses, or migrated to other systems was a natural byproduct.
This change does the following:
*   Remove sites that no longer exist or no longer use Hakyll.
*   Remove sites whose source code is no longer public.
*   Updated addresses for sites and/or source code repositories.
*   Change `http` addresses to `https` addresses when possible.
*   There are no more Hakyll 3 sites; they have all moved to Hakyll 4, migrated to other systems, or disappeared.
=> Clean up examples.

.github/workflows/main.yml
easy-file 0.2.5 fixes the build issue that 0.2.4 had, so we can re-enable the affected compilers now.
Fixes #988.
=> CI: re-enable GHC <8.10.6 on Windows

data/templates/feed-item.json, data/templates/feed.json, hakyll.cabal, lib/Hakyll/Web/Feed.hs, lib/Hakyll/Web/Template/Context.hs, web/tutorials/05-snapshots-feeds.markdown
> The JSON Feed format is a pragmatic syndication format, like [RSS](http://cyber.harvard.edu/rss/rss.html) and [Atom](https://tools.ietf.org/html/rfc4287), but with one big difference: it’s JSON instead of XML.
This PR adds JSON Feed support to Hakyll with a pretty barebone template, conforming to the [JSON Feed 1.1 spec](https://www.jsonfeed.org/version/1.1/). I have deployed it to my [personal blog](https://ozkutuk.me/feed.json) to serve as a working example, and it seems to work without any issues.
=> Add JSON Feed support

.github/workflows/main.yml
The issue in the network package seem to be fixed, so let's retry the build.
Fixes #986.
=> CI: re-enable GHC 9.6.1 on Windows

lib/Hakyll/Core/Runtime.hs, tests/Hakyll/Core/Runtime/Tests.hs
=> Add errors for multiple writes to the same file

hakyll.cabal
Tested with GHC 9.2.8 and `for action in build test ; do cabal $action --enable-tests --constrain 'tasty == 1.5' || break ; done` — all tests pass fine.
=> Allow tasty 1.5

web/tutorials/using-clay-with-hakyll.markdown
Kudos to @JHaugh4 for spotting this and providing the correct link.
Fixes #1005.
=> Fix broken link to Clay preprocessor

hakyll.cabal
Tested with `for action in build test ; do cabal $action --enable-tests --constrain 'bytestring == 0.12.0.2' || break ; done`.
=> Allow bytestring 0.12

hakyll.cabal
Tested with GHC 9.4.8: `for action in build test ; do cabal $action --enable-tests --constrain 'text == 2.1' || break ; done`.
=> Allow text 2.1

hakyll.cabal
Tested with `for action in build test ; do cabal $action --enable-tests --constrain 'file-embed == 0.0.16.0' || break ; done` with GHC 9.4.8 on Linux.
=> Allow file-embed 0.0.16

hakyll.cabal
Tested with GHC 9.8.2:
```
for action in build test ; do cabal $action --enable-tests --flags '+previewServer' --constrain 'warp == 3.4.0' || break ; done
```
=> Allow warp 3.4

hakyll.cabal
This PR simply loosens the upper bound on `filepath`  to allow version 1.5
=> Allow filepath-1.5

web/tutorials/faq.markdown
I got an error 
```
Store.set: invalid argument (cannot decode byte sequence starting from 197)
```
This is different from the encoding errors listed, but I was still able to solve it by setting `LANG`.
EDIT: I added the error after the other two because I can't tell whether it happens during read or write.
=> faq: Add another possible encoding error

hakyll.cabal, lib/Hakyll/Commands.hs
-  Make these flags manual so they can't be turned off by cabal without the user knowing about it.
-  Improve error message to mention how to override them in `cabal.project`.
See #1022
=> Improve +watchServer and +previewServer flags

lib/Hakyll/Core/Routes.hs
[Text styles](https://haskell-haddock.readthedocs.io/latest/markup.html?highlight=bold#emphasis-bold-and-monospaced-styled-text) do not get applied when the source is not on the same line.  This commit fixes the bold formatting while preserving the [80 character line limit](https://github.com/jaspervdj/hakyll/pull/911#pullrequestreview-829657363).
=> Hakyll.Core.Routes: fix bold formatting

lib/Hakyll/Web/Template/Context.hs, web/tutorials/04-compilers.markdown
Hakyll.Web.Template.Context
- add examples to the fields
- add explanation about replacing `defaultContext` fields
'More on compilers: load, and templates' tutorial
- add `$title$` to the list of fields in `defaultContext`
- add explanation about replacing `defaultContext` fields
=> explain fields in `defaultContext`

hakyll.cabal
Tested with GHC 9.8.2 and `for action in build test ; do cabal $action --enable-tests --constrain 'pandoc == 3.2' || break ; done`.
=> Allow pandoc 3.2

.github/workflows/main.yml, hakyll.cabal, lib/Hakyll/Core/Runtime.hs, src/Init.hs
Bump the upper bound on template-haskell and enable CI for GHC-9.10.1.
Tested locally with GHC 9.10: All the tests run through. A metadata revision or minor release would be much appreciated :)
=> Compatibility with GHC 9.10

hakyll.cabal
`for action in build test ; do cabal $action --enable-tests --constrain 'pandoc == 3.4' || break ; done` passed.
=> Allow pandoc 3.4

hakyll.cabal
`for action in build test ; do cabal $action --enable-tests --constrain 'pandoc == 3.5' || break ; done` passed with GHC 9.8.2
=> Allow pandoc 3.5

lib/Hakyll/Web/Pandoc.hs
Add `renderPandocItemWithTransformM` and `pandocItemCompilerWithTransformM`, which work like the respective functions without the "item" infix, but the transformation function is a monadic "Item Pandoc -> Item Pandoc" instead of just a "Pandoc -> Pandoc". This allows one to more seamlessly compose functions that do require the extra information that an item provides, like bibliographic transformations.
---
My specific use-case for this is exactly adding a nicely formatted bibliography at the end of certain pages.
Here is a real world example with entirely too much code:
``` haskell
myPandocCompiler :: Compiler (Item String)
myPandocCompiler =
pandocItemCompilerWithTransformM                     -- ⋘ HERE
readerOpts
writerOpts
(traverse moreSettings <=< processBib)
where
processBib :: Item …
```
=> Add variants of pandoc renderer and compiler for items

lib/Hakyll/Web/Template/Context.hs
This is useful if the value of the field depends on item's metadata, for instance, which is best queried in a `MonadMetadata`, which `field'`s type fixes to be a `Compiler`.
=> Add `boolFieldM` for `Compiler`-dependent bool fields

.github/workflows/hlint.yml, .hlint.yaml
I thought it would be nice to have a linter, so this adds an [HLint](https://github.com/ndmitchell/hlint) workflow which [uploads its results to GitHub code scanning](https://github.com/haskell-actions/hlint-scan).  If you do not want a linter or prefer other ways to do linting, feel free to close this pull request without merging.
This change disables hints that would trigger for the existing code.  Depending on preference, some of them can be enabled later, while others could be permanently disabled.  E.g., removing a needless `$` seems a good idea, while I am not a fan of the suggestion to use `<&>` with Hakyll code.
To see what warnings and suggestions may look like, see https://github.com/haskell-actions/hlint-scan#examples.
=> Use HLint.

web/css/default.css, web/templates/default.html
This updates the HTML and stylesheet for the Hakyll website to better accommodate small screens, i.e., phones and such.  I feel like it's time it got the [same treatment](https://github.com/jaspervdj/hakyll/commit/9ce4870a3793b362ba2b5ff66a5957ac27c5ddb2) that the starter site did.
*   It leaves styling for bigger screens alone for the most part, except for using a `max-width` so that the width can be smaller on narrower displays, i.e., phone screens or narrow web browser windows.
*   It sets `viewport` in the HTML so that the styling will be based on the real dimensions of the screen, not the fake dimensions used by phones to display websites specifically tailored to a certain size on desktops.
*   On narrow screens, it overrides properties so that the presentation is better for a narrow …
=> Style Hakyll website to better accommodate smaller screens.

CHANGELOG.md, hakyll.cabal, lib/Hakyll/Web/Pandoc/Biblio.hs
Adds support for pandocs [nocite](https://pandoc.org/chunkedhtml-demo/9.6-including-uncited-items-in-the-bibliography.html) functionality by having an appropriate field in the metadata of the site:
nocite: |
@citation1
@citation2
…
This adds `pandoc-types` as an explicit dependency, but it was already transient before that, so it's not really new. I also wrote some documentation (in a separate commit, but feel free to squash) so more people can understand how to actually use these functions.
=> `processPandocBiblio`: Honour `nocite` directives

lib/Hakyll/Core/Util/File.hs
This is a quick followup to bdfbead07f80ac057323c4418a0b4641aec34d25. No functional changes.
=> Fix typo, remove trailing whitespace, reword documentation (#1062)

CHANGELOG.md, lib/Hakyll/Core/Util/File.hs
This is mostly for fixing #1061 but it also addresses some concerns discussed in #1062
=> Do not return broken symlinks from getRecursiveContents (#1061, #1062)

lib/Hakyll/Core/Util/String.hs, tests/Hakyll/Core/Util/String/Tests.hs
`(=~~)` is polymorphic in its return type. Get first match + before/after directly, instead of splitting manually on match indices. Moreover, since `=~~` uses `'fail'` on lack of match, and `Maybe` is an instance of `MonadFail`, `listToMaybe` isn't necessary.
=> Simplify replaceAll and splitAll in Hakyll.Core.Util.String

hakyll.cabal
Fixes #1071 
I tested locally using `cabal test --constraint="pandoc==3.7"`.
=> Bump pandoc dependency bounds to include 3.7

hakyll.cabal
This was tested manually using:
```
cabal test --constraint="QuickCheck==2.16.0.0"  --allow-newer=QuickCheck
```
Note that `allow-newer` is required since `tasty-quickckeck` doesn't yet support QuickCheck 2.16
See https://github.com/commercialhaskell/stackage/issues/7778
=> Allow QuickCheck 2.16

hakyll.cabal, lib/Hakyll/Web/Pandoc.hs
This PR adds support for pandoc-3.8 in hakyll.
Note that pandoc 3.8 changed the way syntax highlighting is specified in `WriterOptions`. Therefore, to support pandoc 3 - 3.8 inclusively, we need to use CPP :(
I tested locally that Hakyll now compiles with pandoc 3.6 and pandoc 3.8 using:
```
cabal test --constraint="pandoc<=3.6"
cabal test --constraint="pandoc>=3.8"
```
which both passed all tests.
Fixes #1079
=> Support for pandoc 3.8
