src/Hakyll/Web/Template/Context.hs

Make it easy to create Boolean fields from Boolean functions.

Add boolField

---

web/examples.markdown

Signed-off-by: Collin J. Doering <collin.doering@rekahsoft.ca>

Added blog.rekahsoft.ca to examples

---

src/Hakyll/Commands.hs

Signed-off-by: Magnus Therning <magnus@therning.org>

Fix a typo in disabled preview server function.

---

src/Hakyll/Web/Pandoc.hs
src/Hakyll/Web/Pandoc/FileType.hs

This is pretty close to completely untested, but may work. I'm submitting it as a pull request only because it may be useful to the orignal asker of this question: https://groups.google.com/forum/#!topic/hakyll/Y2oSt2smrn8

let pandoc handle DocBook files

---

src/Hakyll/Core/Compiler.hs

Improve documentation of getResourceXXX functions.

---

web/examples.markdown

I also updated [my tutorial](http://sigkill.dk/writings/guides/hakyll.html), but I'm not really sure where it would fit.

sigkill.dk now uses Hakyll 4.

---

data/example/site.hs
src/Hakyll/Web/Template.hs
tests/Hakyll/Web/Template/Tests.hs
web/tutorials/04-compilers.markdown

templateCompiler compiles resource body only

---

src/Hakyll/Core/UnixFilter.hs

Fixes #408: Documentation for "unixFilter" now compiles

---

web/examples.markdown

Shameless plug of my Hakyll-based blog

Add raindev.io to the list of examples

---

web/examples.markdown

A material design theme port for Hakyll

Add new entry to hakyll blog examples

---

src/Hakyll/Check.hs

As reported in #334, sometimes the `Exception`s litter the terminal with unnecessary details. This commit will make errors output in the form `404 Not Found` for `StatusCodeException` and `SomeOtherException` for other exceptions.
I tried to honour the 80 character-limit; if you find some formatting or other issues or have a better idea how to get the exception name, I can rebase it.
Also it fixes `SIGINT`, thanks to @​Yuras on [StackOverflow](http://stackoverflow.com/a/38032304/160386).

Make errors in Check less verbose

---

src/Hakyll/Web/Template/Internal.hs

This should fix the second problem in #376.

Fail if template is not parsed until eof

---

hakyll.cabal
src/Hakyll/Main.hs

changed shell options parser from cmdAgrs to Options.Applicative

cmdArgs to Options.Applicative

---

src/Hakyll/Web/Feed.hs

Fix a bug when renderAtom and renderRss generate broken XML when the item contains CDATA blocks.

Fix feed generator when item contains CDATA

---

web/examples.markdown

Hi, Jasper!
I have added alexanderlobov.ru an an example of site using Hakyll.

Added alexanderlobov.ru to examples

---

src/Hakyll/Check.hs

Make url check concurrent

---

web/examples.markdown

Added brandonstil.es to examples
Thanks for creating Hakyll!

Added brandonstil.es to examples

---

web/examples.markdown

Hi @jaspervdj ! I wanted to add my blog to the examples if you don't mind 🙏

Add anler.me to examples

---

src/Hakyll/Main.hs

Closes #400.
Two functions added:
* 'hakyllWithArgs' exported which expects the command line arguments
to be given by the user.
* 'hakyllWithExitCodeAndArgs' used internally selects the relevant
arguments and invokes the commands.

Enable bypassing of argument parsing

---

web/examples.markdown
web/tutorials/external-blogger-port.md
web/tutorials/external-cassius-template.md

So I just wrote this two tutorials:
- Port an existing Blogger blog to Hakyll
- Using Cassius template with Hakyll

Add tutorials

---

web/examples.markdown

Add website of the Russian podcast about Haskell.

Add bananasandlenses.net

---

src/Hakyll/Web/CompressCss.hs
tests/Hakyll/Web/CompressCss/Tests.hs

I had these sitting on my computer for ages and almost forgot about them, so here they finally are.

Some small CSS compression improvements

---

lib/Hakyll/Main.hs

Expose hakyllWithExitCodeAndArgs, Options, and Command.

---

src/Init.hs

Resolves #503 
```
$ stack exec hakyll-init -- ../test-test
The following files will be overwritten:
../test-test/../test-test/test-test.cabal
../test-test/about.rst
../test-test/contact.markdown
../test-test/css/default.css
../test-test/images/haskell-logo.png
../test-test/index.html
../test-test/posts/2015-08-12-spqr.markdown
../test-test/posts/2015-10-07-rosa-rosa-rosam.markdown
../test-test/posts/2015-11-28-carpe-diem.markdown
../test-test/posts/2015-12-07-tu-quoque.markdown
../test-test/site.hs
../test-test/templates/archive.html
../test-test/templates/default.html
../test-test/templates/post-list.html
../test-test/templates/post.html
Use -f to overwrite them
$ stack exec hakyll-init -- -f ../test-test
Creating ../test-test/about.rst
Creating ../test-test/contact.markdown
Creating …
```

Added overwritten files check

---

lib/Hakyll/Core/UnixFilter.hs
tests/Hakyll/Core/UnixFilter/Tests.hs

Make unixFilter output stderr when failing

---

lib/Hakyll/Web/Html.hs

Add withTagList

---

hakyll.cabal
lib/Hakyll.hs
lib/Hakyll/Core/Util/Parser.hs
stack.yaml
tests/Hakyll/Core/Rules/Tests.hs
tests/Hakyll/Core/Runtime/Tests.hs
tests/Hakyll/Web/Template/Tests.hs
tests/TestSuite.hs
tests/TestSuite/Util.hs

Cuts down my build size from 41,005,585 Bytes to 31,203,857 Bytes.

make pandoc optional

---

web/examples.markdown

I've added my Hakyll-based site (and the source) to the examples page.

Update examples.markdown with new site

---

src/Init.hs

Get rid of foldMap for older GHC

---

lib/Hakyll/Web/Pandoc/Biblio.hs

Fix path resolution in Pandoc.Biblio

---

hakyll.cabal

Builds fine and all tests pass.

Allow yaml 0.9

---

web/libraries.markdown

it works well with npm-provided libraries, such as bootstrap

add hakyll-sass to the list of haykll libraries

---

hakyll.cabal
lib/Hakyll/Core/Store.hs
stack.yaml

- Bump yaml to 0.11
- Bump pandoc to 2.4
- Bump pandoc-citeproc to 0.15

Bump dependencies

---

hakyll.cabal

All tests pass. 0.0.11 is a release with new feature only.

Allow file-embed 0.0.11

---

web/tutorials/01-installation.markdown

Unfortunately there is no detail page for the Nix package as I know, so I put a link to the Nix package search and the install command, but I am grateful for suggestions as well.

Add Nix Package

---

web/tutorials/robertwpearce-05-generating-custom-post-filenames-from-a-title-slug.html

Post: https://robertwpearce.com/hakyll-pt-5-generating-custom-post-filenames-from-a-title-slug.html

robertwpearce: hakyll pt 5 tutorial source file

---

lib/Hakyll/Web/Template/Context.hs
tests/Hakyll/Web/Template/Context/Tests.hs
tests/data/posts/2019/05/10/tomorrow.md

I thought this was an option already. Is there any reason not to allow this as a way of specifying date?

Add option to specify date in directory structure

---

hakyll.cabal
lib/Hakyll/Web/Tags.hs
tests/Hakyll/Web/Tags/Tests.hs
tests/TestSuite.hs

Add getCategory tests

---

lib/Hakyll/Web/Tags.hs

Add titles to tag fields

---

.gitignore
CHANGELOG.md
hakyll.cabal
lib/Hakyll/Core/Compiler/Internal.hs
lib/Hakyll/Core/Metadata.hs
lib/Hakyll/Core/Rules/Internal.hs
lib/Hakyll/Web/Template/Context.hs
lib/Hakyll/Web/Template/List.hs
stack.yaml

Add MonadFail instances and constraints.
Resolves #754

Support GHC-8.8

---

lib/Hakyll/Core/Metadata.hs
lib/Hakyll/Core/Rules/Internal.hs
lib/Hakyll/Web/Template/Context.hs
lib/Hakyll/Web/Template/List.hs

This fixes v4.13.1.0 on GHC 8.6
Closes #759

Add MonadFail imports

---

hakyll.cabal

I've tested, it seems to work.

raise upper bound for pandoc-citeproc

---

hakyll.cabal

Builds fine and all tests pass.

Allow cryptonite 0.27

---

hakyll.cabal

Builds fine and all tests pass here.

Allow file-embed 0.0.12

---

hakyll.cabal

Builds fine and all tests pass here.

Allow random 1.2

---

src/Init.hs

Fix https://github.com/jaspervdj/hakyll/issues/801

Make sure the initial project is writable

---

web/tutorials/github-pages-tutorial.md

As discussed with Minoru earlier today.

Issue #822: change tutorial to reflect recent GH Pages features

---

hakyll.cabal

Allow file-embed 0.0.13

---

hakyll.cabal
lib/Hakyll/Web/Pandoc/Biblio.hs
lib/Hakyll/Web/Pandoc/Binary.hs
stack.yaml
stack.yaml.lock

Tested using https://github.com/jaspervdj/hakyll-citeproc-example
Fixes #812

Pandoc 2.11 compatibility

---

hakyll.cabal
tests/Hakyll/Web/Pandoc/Biblio/Tests.hs
tests/TestSuite.hs
tests/data/biblio/biblio01.golden
tests/data/biblio/chicago.csl
tests/data/biblio/default.html
tests/data/biblio/page.markdown
tests/data/biblio/refs.bib

As promised in https://github.com/jaspervdj/hakyll/pull/826#issuecomment-739542423, this PR turns https://github.com/jaspervdj/hakyll-citeproc-example into an actual test.

Add golden test for Pandoc.Biblio

---

lib/Hakyll/Web/Pandoc/Biblio.hs

Resolves #802 
I've not used the documentation formatting before so it could be incorrect and I'd appreciate the check.

Add documentation for the pandocBiblioCompiler

---

web/examples.markdown

I really enjoy using Hakyll. Thanks for this great library !

Add jeancharles.quillet.org to examples

---

web/examples.markdown

Figured I would add my site into the examples page too, it helps with SEO :)
Thanks for the awesome library!

add nliu.net to examples for shameless self-promotion

---

web/tutorials/01-installation.markdown

Fix binary's name in the first tutorial

---

hakyll.cabal

Pandoc 2.14 was released a few days ago

Allow Pandoc 2.14

---

.github/workflows/main.yml

https://github.com/actions/setup-haskell has been archived.
I believe https://github.com/haskell/actions/tree/main/setup is current.

update Github Actions

---

web/templates/tutorial.html

Kudos to Philippa on IRC for spotting this!

Fix IRC link on the website

---

lib/Hakyll/Core/Runtime.hs

As part of the implementation of the concurrent runtime, the state
parameter of the `Runtime` `RWST` changed from `RuntimeState` to
`MVar RuntimeState`.  As a result, that value is now read-only.
Furthermore, the writer parameter is unused (`()`).
Therefore, we do not need `RWST`; `ReaderT` suffices.  Add a new
field to `RuntimeRead` to hold the `MVar RuntimeState`, and populate
it.  Change `Runtime` to `ReaderT` and update the `getRuntimeState`
and `modifyRuntimeState` functions to reference the new field.

runtime: simplify Runtime type (RWST → ReaderT)

---

lib/Hakyll/Core/Runtime.hs

The runtime code includes some unnecessary conversions between `[]`
and `Set`.  Avoid these conversions.  Besides simplifying the code,
this change yields a small performance improvement:
```
% hyperfine \
--prepare './site-4.14.1   clean' './site-4.14.1   build' \
--prepare './site-set-conv clean' './site-set-conv build'
Benchmark #1: ./site-4.14.1 build
Time (mean ± σ):      6.689 s ±  0.101 s    [User: 6.425 s, System: 0.256 s]
Range (min … max):    6.596 s …  6.935 s    10 runs
Benchmark #2: ./site-set-conv build
Time (mean ± σ):      6.647 s ±  0.046 s    [User: 6.344 s, System: 0.295 s]
Range (min … max):    6.576 s …  6.719 s    10 runs
Summary
'./site-set-conv build' ran
1.01 ± 0.02 times faster than './site-4.14.1 build'
```

runtime: avoid unnecessary set/list conversions

---

lib/Hakyll/Core/Compiler.hs

If a Hakyll program termiantes abnormally (e.g. due to kill signal),
a subsequent run can fail because expected cache entries are not
present.  The missing cache entry is regarded as corruption; Hakyll
advises the user to delete the cache and start over.
But this scenario is recoverable, and the user need not be bothered.
If `Store.get` returns `NotFound`, don't fail - compile the item!
Other results (e.g. `WrongType`) still throw an error.

tolerate unexpected cache miss

---

lib/Hakyll/Core/Runtime.hs
tests/Hakyll/Core/Runtime/Tests.hs

Better detection of dependency cycles

---

lib/Hakyll/Core/Identifier.hs

Extend identifier documentation

---

web/examples.markdown

Includes an advanced gallery functional
@jaspervdj

Add my site to list of examples

---

lib/Hakyll/Core/Routes.hs

Extend Routes docs

---

.github/workflows/main.yml

Perhaps it fixed our build failures on Windows.

Try GHC 9.0.2

---

lib/Hakyll/Core/Rules.hs

Extend rules docs

---

web/examples.markdown

Hi! 
First of all, thanks a lot for developing Hakyll!
The code of my personal website is now public, and I thought I would share it here too in case someone wants to take a look at it. 
The automatic build and deploy using GitHub actions took me a bit to understand, so this perhaps can save someone else some time :)

Added new website example

---

lib/Hakyll/Web/Tags.hs

Export Hakyll.Tags.simpleRenderLink

---

lib/Hakyll/Web/Pandoc/Biblio.hs

`pandocBiblioCompiler` is allowed to take multiple bib files by glob. It should be backwards-compatible.

`pandocBiblioCompiler` loads multiple bib files by glob

---

lib/Hakyll/Core/Store.hs
stack.yaml
stack.yaml.lock

fix: IORef to skip concurrent writes in Store.set

---

lib/Hakyll/Web/Html.hs

I needed to do something with the tag list while maintaining some state, so it feels natural to add a combinator for that!

Add a monadic version of withTagList

---

web/examples.markdown

Adding my blog into list of examples, btw thanks for the package, hakyll is amazing

add aerphanas.github.io to to examples

---

hakyll.cabal

This PR brings support for pandoc 3.1 (current latest release is 3.1.1)

Add support for pandoc 3.1

---

web/tutorials/robertwpearce-07-the-hakyll-nix-template-tutorial.html

Hi!
I put together the [hakyll-nix-template](https://github.com/rpearce/hakyll-nix-template/) some time ago. It is a reasonable way to get started with nix and hakyll, and I've made a good number of updates that I thought merited a tutorial.
I think the hakyll defaults in the project are fairly useful, and the next thing I'm doing for the template, for example, will be hashing content (like CSS) and using that to break caches on CSS, JS, etc. If and when that happens, this tutorial will be updated!
I've enjoyed hakyll, and I appreciate being able to extend it to do what I want. For example, I use post titles to generate HTML slugs, but I wasn't satisfied with what the Haskell ecosystem offered, so I wrote my own (https://hackage.haskell.org/package/slugger), released it, and use it via …

Add robertwpearce Tutorial: The hakyll-nix-template Tutorial

---

web/examples.markdown
web/tutorials/external-alternative-syntax-highlighting.md
web/tutorials/external-bibtex.md
web/tutorials/external-sidenotes.md

Hi,
apologies for lumping two sort of independent commits into one PR; they are very small, so separate PRs seemed unwarranted to me.

Add example website and tutorials

---

web/tutorials/01-installation.markdown

Consolidating information from:
- https://github.com/NixOS/nix/issues/318
- https://github.com/jaspervdj/hakyll/issues/614

Add some docs on how to ensure proper locale access in hakyll

---

web/templates/tutorial.html

Reference: [Make link text meaningful](https://www.w3.org/WAI/tips/writing/#make-link-text-meaningful)

tutorial: Make link text descriptive

---

.github/workflows/main.yml
stack.yaml
stack.yaml.lock

bump snapshot in stack lock file: 21.6 -> 21.25

---

web/examples.markdown

Add a link to https://sahel13.github.io.

Add example website.

---

web/tutorials/01-installation.markdown

- Changed `installation.makdown` file in `web` directory and changed links in there.

Updated links of distribution packages in docs

---

web/tutorials/external-server-side-katex-rendering.md

A short article I've written for all the LaTeX enthusiasts out there who don't want to burden their users with client-side rendering

tutorial: Add server-side KaTeX integration

---

web/examples.markdown

Hi, I would like to propose adding my website to the list of Hakyll usage examples. 
It demonstrates that Hakyll can be used to build a structure where multiple blogs coexist on a single site.
I believe this could serve as a useful example for other users, so I would appreciate it if you could consider including it.

Add example website
